steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-prediction-kartik/sales-predictor:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to Artifact Registry'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-prediction-kartik/sales-predictor:$SHORT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-prediction-kartik/sales-predictor:$SHORT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars', 'VERSION=$SHORT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Trigger Cloud Deploy Release'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'releases', 'create', 'release-$SHORT_SHA',
        '--delivery-pipeline', 'sales-predictor-pipeline',
        '--region', 'us-central1',
        '--images', 'sales-predictor=us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-prediction-kartik/sales-predictor:$SHORT_SHA',
        '--source', 'deploy/'
      ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE_NAME: sales-predictor-service
